SELECT
    PROF_ID,
    PRPR_ID,
    PROF_DAY_OF_WK,
    PROF_OPEN_TM,
    PROF_CLOSE_TM,
    SYS_LAST_UPD_DTM,
    _SNOWFLAKE_INSERTED_AT,
    _SNOWFLAKE_UPDATED_AT,
    _SNOWFLAKE_DELETED
FROM {{ source('raw', 'CMC_PROF_OFF_HRS') }}
