name: caloptima_dw
version: '1.0.0'
config-version: 2
profile: caloptima_dw

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]

models:
  caloptima_dw:
    staging:
      +materialized: view
      +schema: STAGING
    intermediate:
      +materialized: ephemeral
    silver:
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: sync_all_columns
      +schema: SILVER
      +transient: false
    gold:
      +materialized: view
      +schema: GOLD
    ops:
      +materialized: table
      +schema: DQ
