name: caloptima_dw
version: '1.0.0'
config-version: 2
profile: caloptima_dw

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]

vars:
  target_database: FACETS_DEV
  silver_schema: SILVER
  bronze_database: FACETS_BRONZE
  bronze_schema: RAW

models:
  caloptima_dw:
    staging:
      +materialized: view
      +database: "{{ var('target_database') }}"
      +schema: STAGING
    intermediate:
      +materialized: ephemeral
    silver:
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: sync_all_columns
      +database: "{{ var('target_database') }}"
      +schema: "{{ var('silver_schema') }}"
    marts:
      +materialized: table
      +database: "{{ var('target_database') }}"
      +schema: "{{ var('silver_schema') }}"
