-- Quarantine table for provider records with invalid NPIs.
-- Populated separately; referenced in silver_provider logic for future triage.
CREATE TABLE IF NOT EXISTS FACETS_DEV.SILVER.BRONZE_QUARANTINE (
    QUARANTINE_ID       NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_TABLE        VARCHAR(100),
    SOURCE_PK_VALUE     VARCHAR(100),
    REJECTION_RULE      VARCHAR(100),   -- 'NPI_INVALID', 'NPI_NULL', 'DEMO_KEY_DUP'
    RAW_RECORD          VARIANT,
    QUARANTINE_DTM      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_DTM        TIMESTAMP_NTZ,
    RESOLVED_BY         VARCHAR(50)
);

-- View: providers currently in quarantine awaiting NPI remediation
CREATE OR REPLACE VIEW FACETS_DEV.SILVER.BRONZE_QUARANTINE_OPEN AS
SELECT *
FROM FACETS_DEV.SILVER.BRONZE_QUARANTINE
WHERE RESOLVED_DTM IS NULL
ORDER BY QUARANTINE_DTM DESC;
